ALTER TABLE assets
ADD COLUMN is_liquid BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN category_id INTEGER NOT NULL DEFAULT 1,
ADD COLUMN adquisition_date TIMESTAMP NOT NULL DEFAULT NOW(),
ADD FOREIGN KEY (category_id) REFERENCES categories(id);